# Generated by Django 6.0.4 on 2026-05-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(choices=[('single', 'Single'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('family', 'Family')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price_family',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price_medium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price_single',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='size',
            field=models.CharField(choices=[('single', 'Single'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('family', 'Family')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(choices=[('single', 'Single'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('family', 'Family')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_items/'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'food_item', 'selected_size')},
        ),
    ]
